### PR TITLE
Create zh_CN file for the mod

### PR DESCRIPTION
**Pull request by TartaricAcid**
Please don't merge it before @Forestwhites approve.

### CODE REVIEW

**Comment by Forestwhites** [comment]
在weblate上面翻译，https://weblate.replaymod.com/projects/replay-mod/minecraft-mod/

**Comment by TartaricAcid** [comment]
我不管了，你加油吧，虽然我觉得github是一个挺不错的方式。

**Comment by Johni0702** [comment]
Please keep comments on GitHub issues and PRs in English, otherwise I'll have no idea what you're saying.

@TartaricAcid ordinarily we manage translations via weblate (see link posted by Forestwhites). It will also push changes to this repo (with the author of the translations properly credited in the commit). 
Note that it will only push when triggered manually by administrators. That way it will prevent lots of tiny commits being generated with ever edit.

Now, if the language file in this PR was completely translated by you, I can tell weblate to push its changes, then merge this PR and weblate will pick up on the new translations. Otherwise, the person who authored those translations should upload them via weblate (there is a function to upload whole files).

**Comment by TartaricAcid** [comment]
Sorry for it, I will upload the files to the weblate.

**Comment by Johni0702** [comment]
If you authored those translations, then there's no need for you to use weblate, GitHub PRs are fine.

**Comment by TartaricAcid** [comment]
Yes, I authored those translations.

**Comment by Johni0702** [comment]
Actually, now that weblate has pushed all changes, II realize that you two did translate things differently which makes for a merge conflict that is rather hard to resolve for someone not speaking Chinese.

I think it'll be easier if you [uploaded your file to weblate](https://weblate.replaymod.com/projects/replay-mod/minecraft-mod/zh_Hans/#upload), so weblate can do the merging.

**Pull request closed without merging**
